### PR TITLE
Support for len, [] and iteration on Collections. Closes #83

### LINKED ISSUE #83: Make Java collections iterable and indexable in Python
I'd like the following code to work

```
javabridge.start_vm(run_headless=True)
a = javabridge.JClassWrapper('java.util.ArrayList')()
a.add(1)
a.add(2)

for x in a:
  print a

assert len(a) == 2
assert a[0] == 1
```

I'm happy to try and implement this but would need some strong guidance in how to get started.

### PR DESCRIPTION
**Pull request by jbcoe**

### CODE REVIEW

**Comment by jbcoe** [comment]
Apologies for noise on this. Made a mess merging.

**Comment by LeeKamentsky** [comment]
np keep going

**Comment by jbcoe** [comment]
If you can very quickly see why Python 3 tests are failing with:
```
======================================================================
ERROR: test_01_02_iterate (javabridge.tests.test_wrappers.TestJClassWrapper_Collection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/LeeKamentsky/python-javabridge/javabridge/tests/test_wrappers.py", line 65, in test_01_02_iterate
    for x,y in zip(self.a, self.ints):
TypeError: zip argument #1 must support iteration
```
While Python 2 tests pass. I'd be grateful. Otherwise this looks close to completion.

**Comment by LeeKamentsky** [comment]
I feel for you: https://www.python.org/dev/peps/pep-3114/

In Python 3, `next()` is `__next__()`
so the following should fix.

    def __next__(self):
        return self.next()

**Comment by jbcoe** [comment]
Ready for a squash-merge.

**Comment by LeeKamentsky** [comment]
Thanks jb - nice sugar and it was kind for you to take responsibility for doing it all.

**Pull request merged**
