### PR TITLE
Remove need to preinstall numpy

### PR DESCRIPTION
**Pull request by altendky**
#30

### CODE REVIEW

**Comment by LeeKamentsky** [comment]
Hi Kyle,
Thanks for looking at javabridge. I'm wondering if you wanted to talk about numpy and javabridge. Javabridge uses numpy currently to support Java numeric arrays efficiently - the initial use-case for Javabridge was to support transfer of image data between Java and Python. There's quite a lot of mechanism beyond what's in setup.py, mostly in _javabridge.pyx, so removing numpy or making it optional is going to be a bit of work.

--Lee

**Comment by altendky** [comment]
@LeeKamentsky I'm just barely starting to fiddle with javabridge and am interested in it for use with the [CCStudio DSS library](http://software-dl.ti.com/ccs/esd/documents/users_guide/sdto_dss_handbook.html).

My plan here wasn't to avoid needing numpy but to avoid the manual preinstall step.  The `setup_requires` should get it installed for (later) use in setup.py and the `install_requires` should get it installed for use by the installed library.  Moving the numpy import into `ext_modules()` and moving the call of `ext_modules()` into the `build_ext` command moves them both after the `setup_requires` are satisfied such that numpy is installed before it is imported in setup.py.

I don't know how complete the automated tests are but I will admit that I can't vouch for this working yet beyond installation since I am just now writing my first code using javabridge.

**Comment by LeeKamentsky** [comment]
That is excellent - it looks like your branch passes the automated tests, so it's a win for the project and something that always bugged me.

**Comment by altendky** [comment]
I wouldn't expect you to kick out a release just for me...  but any guesses on this getting released to PyPi?  Otherwise I'll try to package up my own dist and share on my personal pip repo.

So far this is working quite nicely for me with the `JClassWrapper`.  I'm really glad I ran into issues with Jython, I expect javabridge to be a much better solution for me.

**Comment by LeeKamentsky** [comment]
There have been a couple of good additions in recent weeks, so maybe it's time to cut a release. Javabridge definitely has its place in the Python ecosystem - hope you enjoy.

**Pull request merged**
