### PR TITLE
Change JNI_OnLoad return type modifiers to build with win32 x86

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
Maybe try to rebuild https://travis-ci.org/LeeKamentsky/python-javabridge/builds/362345633?  It failed again with the conda segfault.

I can't say I know anything about this beyond it making it not throw an error with my Windows 32-bit Python install.  I feel like we need more tests, but if you are comfortable with this...  Regardless, if you create a build linked to this repo on AppVeyor I can certainly submit a PR to build there to get basic Windows coverage.

**Comment by altendky** [comment]
@LeeKamentsky It installed ok for me on Linux. could you try triggering the build to run again?  Any other opinions on this?

**Comment by LeeKamentsky** [comment]
Oh jeez - just got around to this. Sorry it took so long. Thx Kyle.

**Comment by altendky** [comment]
No worries, I've been bouncing around myself.  Thanks.

**Pull request merged**
